version: '3.6'
services:
   app:
     build:
      context: .
     ports:
       - "8000:8888"
     volumes:
       - /home/django/logs:/logs:rw
       - /home/django/project3_new/static/:/usr/src/app/static/:rw
     depends_on:
       - mysqldb

   nginx:
     build:
      context: ./nginx
     ports:
       - "80:80"
     volumes:
       - /home/django/project3_new/static/:/usr/src/app/static/:rw
       - /home/django/project3_new/logs/:/var/log/nginx/:rw
       - /home/django/project3_new/nginx/suduko_build/:/usr/src/app/suduko_build/:rw
     depends_on:
       - app


   mysqldb: 
      image: mysql
      ports: 
        - "3306:3306"
      volumes: 
        - /home/dov/data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=tortola1 

